
import 'dart:convert';
import 'dart:io';
import 'package:encrypt/encrypt.dart' as encrypt;
import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:get/get.dart';
import 'package:healthpost_app/models/doctor_appointment.dart';
import 'package:healthpost_app/services/encryption_service.dart';
import 'package:image_picker/image_picker.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:video_player/video_player.dart';

class ChatScreen extends StatefulWidget {
  final DAppt appt;
  const ChatScreen({super.key, required this.appt});

  @override
  State<ChatScreen> createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  final _supabase = Supabase.instance.client;
  final _secureStorage = const FlutterSecureStorage();
  final _messageController = TextEditingController();
  final _scrollController = ScrollController();
  final _picker = ImagePicker();

  List<Map<String, dynamic>> _messages = [];
  String? _conversationId;
  encrypt.Key? _aesKey;
  bool _loading = true;
  bool _sending = false;
  RealtimeChannel? _channel;
  String? _currentUserPrivateKeyPem;

  String get _currentUserId => _supabase.auth.currentUser!.id;
  String get _patientId => widget.appt.patientId;

  @override
  void initState() {
    super.initState();
    _initializeChat();
  }

  @override
  @override
  void dispose() {
    _messageController.dispose();
    _scrollController.dispose();

    if (_channel != null) {
      _supabase.removeChannel(_channel!);
    }

    super.dispose();
  }


  Future<void> _initializeChat() async {
    if (!mounted) return;
    setState(() => _loading = true);
    try {
      await _ensureUserKeyPair();
      _conversationId = await _getOrCreateConversation();
      await _fetchAndDecryptAESKey();
      await _loadMessages();
      _subscribeToMessages();
    } catch (e) {
     if(mounted){
       Get.snackbar('Error', e.toString());
     }
    } finally {
      if(mounted){
        setState(() => _loading = false);
      }
    }
  }


  Future<void> _ensureUserKeyPair() async {
    final profile = await _supabase
        .from('user_profiles')
        .select('public_key')
        .eq('id', _currentUserId)
        .maybeSingle();

    if (profile == null || profile['public_key'] == null) {
      await _generateAndSaveKeyPair();
    } else {
      _currentUserPrivateKeyPem = await _secureStorage.read(
        key: 'rsa_private_key_$_currentUserId',
      );
      if (_currentUserPrivateKeyPem == null) {
        await _generateAndSaveKeyPair();
      }
    }
  }

  Future<void> _generateAndSaveKeyPair() async {
    final keyPair = EncryptionService.generateRSAKeyPair();
    final pubPem = EncryptionService.publicKeyToPem(keyPair.publicKey);
    final privPem = EncryptionService.privateKeyToPem(keyPair.privateKey);

    await _secureStorage.write(
      key: 'rsa_private_key_$_currentUserId',
      value: privPem,
    );
    await _supabase
        .from('user_profiles')
        .update({'public_key': pubPem})
        .eq('id', _currentUserId);

    _currentUserPrivateKeyPem = privPem;
  }

  //  CONVERSATION MANAGEMENT - Each doctor-patient pair has a single conversation. The AES key for that conversation is generated by the first one to create it, encrypted with both parties' RSA public keys, and stored in the conversation record for secure retrieval.

  Future<String> _getOrCreateConversation() async {
   
    final existing = await _supabase
        .from('conversations')
        .select('id')
        .eq('patient_id', _patientId)
        .eq('doctor_id', _currentUserId)
        .maybeSingle();

    if (existing != null) return existing['id'] as String;

    // Fetch both public keys
    final rows = await _supabase
        .from('user_profiles')
        .select('id, public_key')
        .inFilter('id', [_currentUserId, _patientId]);

    final Map<String, String> pubKeys = {
      for (final r in rows) r['id'] as String: r['public_key'] as String,
    };

    if (pubKeys[_patientId] == null) {
      throw Exception(
        'Patient has not set up encryption yet. Ask them to open the app first.',
      );
    }
    if (pubKeys[_currentUserId] == null) {
      throw Exception('Your public key is missing. Please restart the app.');
    }

    final aesKey = EncryptionService.generateAESKey();
    final aesB64 = aesKey.base64;

    final encForPatient = EncryptionService.encryptWithRSA(
      aesB64,
      EncryptionService.parsePublicKeyFromPem(pubKeys[_patientId]!),
    );
    final encForDoctor = EncryptionService.encryptWithRSA(
      aesB64,
      EncryptionService.parsePublicKeyFromPem(pubKeys[_currentUserId]!),
    );

    final response = await _supabase
        .from('conversations')
        .insert({
          'patient_id': _patientId,
          'doctor_id': _currentUserId,
          'aes_key_encrypted_for_patient': encForPatient,
          'aes_key_encrypted_for_doctor': encForDoctor,
        })
        .select('id')
        .single();

    return response['id'] as String;
  }

  //  AES KEY MANAGEMENT - The AES key for the conversation is fetched and decrypted with the doctor's RSA private key on initialization, allowing for secure end-to-end encryption of messages without exposing the AES key to the server.
  Future<void> _fetchAndDecryptAESKey() async {
    final conv = await _supabase
        .from('conversations')
        .select('aes_key_encrypted_for_doctor')
        .eq('id', _conversationId!)
        .single();

    final encKey = conv['aes_key_encrypted_for_doctor'] as String?;
    if (encKey == null) throw Exception('No AES key found in conversation');

    final privKey = EncryptionService.parsePrivateKeyFromPem(
      _currentUserPrivateKeyPem!,
    );
    String aesB64;
    try {
      aesB64 = EncryptionService.decryptWithRSA(encKey, privKey);
    } catch (e) {
      debugPrint('RSA decryption failed: $e');
      await _recreateConversation();
      return;
    }

    if (!_isValidBase64(aesB64)) {
      debugPrint('Invalid AES key base64: "$aesB64"');
      await _recreateConversation();
      return;
    }

    _aesKey = encrypt.Key.fromBase64(aesB64);
  }

  Future<void> _recreateConversation() async {
    debugPrint('Recreating conversation due to key mismatch');
    await _supabase.from('conversations').delete().eq('id', _conversationId!);
    _conversationId = await _getOrCreateConversation();
    await _fetchAndDecryptAESKey(); // retry
  }
  
  bool _isValidBase64(String str) {
    try {
      base64Decode(str);
      return true;
    } catch (_) {
      return false;
    }
  }
  //  MESSAGES - Messages are encrypted with AES before sending and decrypted on receipt. Media messages are supported by uploading files to Supabase Storage and sending the URL in the message record. Realtime updates are handled via Supabase's Realtime channels, with optimistic UI updates for a responsive experience.

  Future<void> _loadMessages() async {
    final data = await _supabase
        .from('messages')
        .select()
        .eq('conversation_id', _conversationId!)
        .order('created_at', ascending: true);
    if (!mounted) return;
    setState(() => _messages = data.map(_decodeMessage).toList());
    _scrollToBottom();
  }
void _subscribeToMessages() {
    final channelName = 'messages:${_conversationId!}:$_currentUserId';

    _channel = _supabase
        .channel(channelName)
        .onPostgresChanges(
          event: PostgresChangeEvent.insert,
          schema: 'public',
          table: 'messages',
          filter: PostgresChangeFilter(
            type: PostgresChangeFilterType.eq,
            column: 'conversation_id',
            value: _conversationId!,
          ),
          callback: (payload) {
            final newRecord = payload.newRecord;

            final alreadyExists = _messages.any(
              (m) => m['id'] != null && m['id'] == newRecord['id'],
            );
            if (alreadyExists) return;
            if (!mounted) return;
            final decoded = _decodeMessage(newRecord);
            setState(() => _messages.add(decoded));
            _scrollToBottom();
          },
        )
        .subscribe((status, [error]) {
          debugPrint('Realtime status: $status, error: $error');
        });
  }


  Map<String, dynamic> _decodeMessage(Map<String, dynamic> msg) {
    if (msg['is_key_exchange'] == true) {
      return {...msg, 'decrypted_content': ' Secure session established'};
    }
    if (msg['media_url'] != null) {
      return {...msg, 'decrypted_content': null};
    }
    try {
      final text = EncryptionService.decryptWithAES(
        msg['encrypted_content'] as String,
        _aesKey!,
        msg['iv'] as String,
      );
      return {...msg, 'decrypted_content': text};
    } catch (_) {
      return {...msg, 'decrypted_content': '[Unable to decrypt]'};
    }
  }

  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  //  SEND MESSAGE - Handles the process of sending an encrypted message, including optimistic UI updates.
Future<void> _sendMessage() async {
    final text = _messageController.text.trim();
    if (text.isEmpty || _aesKey == null) return;
    _messageController.clear();

    final enc = EncryptionService.encryptWithAES(text, _aesKey!);

    // Add optimistically
    final tempMsg = {
      'id': null,
      'conversation_id': _conversationId,
      'sender_id': _currentUserId,
      'encrypted_content': enc.content,
      'iv': enc.iv,
      'media_url': null,
      'media_type': null,
      'is_key_exchange': false,
      'created_at': DateTime.now().toUtc().toIso8601String(),
      'decrypted_content': text,
    };
    if (mounted) {
      setState(() => _messages.add(tempMsg));
    }
    _scrollToBottom();

    final inserted = await _supabase
        .from('messages')
        .insert({
          'conversation_id': _conversationId,
          'sender_id': _currentUserId,
          'encrypted_content': enc.content,
          'iv': enc.iv,
        })
        .select()
        .single();
    if (mounted) {
      setState(() {
        final idx = _messages.indexWhere((m) => m['id'] == null);
        if (idx != -1) {
          _messages[idx] = {...inserted, 'decrypted_content': text};
        }
      });
    }
  }


  Future<void> _pickAndSendImage() async {
    final file = await _picker.pickImage(source: ImageSource.gallery);
    if (file == null) return;
    await _uploadAndSendMedia(File(file.path), 'image');
  }

  Future<void> _pickAndSendVideo() async {
    final file = await _picker.pickVideo(source: ImageSource.gallery);
    if (file == null) return;
    await _uploadAndSendMedia(File(file.path), 'video');
  }
Future<void> _uploadAndSendMedia(File file, String mediaType) async {
    if (_sending) return;
    if(mounted){
      setState(() => _sending = true);
    }
    try {
      final ext = file.path.split('.').last;
      final path =
          'chat/$_conversationId/${DateTime.now().millisecondsSinceEpoch}.$ext';

      await _supabase.storage.from('chat-media').upload(path, file);
      final url = _supabase.storage.from('chat-media').getPublicUrl(path);

      final tempMsg = {
        'id': null,
        'conversation_id': _conversationId,
        'sender_id': _currentUserId,
        'media_url': url,
        'media_type': mediaType,
        'is_key_exchange': false,
        'created_at': DateTime.now().toUtc().toIso8601String(),
        'decrypted_content': null,
      };
      if(mounted){
        setState(() => _messages.add(tempMsg));
      }
      _scrollToBottom();

      final inserted = await _supabase
          .from('messages')
          .insert({
            'conversation_id': _conversationId,
            'sender_id': _currentUserId,
            'media_url': url,
            'media_type': mediaType,
          })
          .select()
          .single();

      if(mounted){
        setState(() {
          final idx = _messages.indexWhere((m) => m['id'] == null);
          if (idx != -1) {
            _messages[idx] = {...inserted, 'decrypted_content': null};
          }
        });
      }
    } catch (e) {
      if(mounted){
        setState(() => _messages.removeWhere((m) => m['id'] == null));
      }
      Get.snackbar('Error', 'Failed to send media: $e');
    } finally {
if(mounted){
  setState(() => _sending = false);
}
    }
  }


  //  BUILD - Constructs the UI for the consultation screen.

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.appt.patientName),
        backgroundColor: const Color(0xFF1565C0),
        foregroundColor: Colors.white,
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : Column(
              children: [
                Expanded(
                  child: ListView.builder(
                    controller: _scrollController,
                    padding: const EdgeInsets.all(12),
                    itemCount: _messages.length,
                    itemBuilder: (_, i) {
                      final msg = _messages[i];
                      return _MessageBubble(
                        msg: msg,
                        isMe: msg['sender_id'] == _currentUserId,
                      );
                    },
                  ),
                ),
                _buildInputArea(),
              ],
            ),
    );
  }

  Widget _buildInputArea() {
    return SafeArea(
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
        decoration: BoxDecoration(
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.06),
              blurRadius: 6,
              offset: const Offset(0, -2),
            ),
          ],
        ),
        child: Row(
          children: [
            IconButton(
              icon: const Icon(Icons.image_outlined),
              onPressed: _pickAndSendImage,
              color: const Color(0xFF1565C0),
            ),
            IconButton(
              icon: const Icon(Icons.videocam_outlined),
              onPressed: _pickAndSendVideo,
              color: const Color(0xFF1565C0),
            ),
            Expanded(
              child: TextField(
                controller: _messageController,
                decoration: InputDecoration(
                  hintText: 'Type a message…',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                    borderSide: BorderSide.none,
                  ),
                  filled: true,
                  fillColor: Colors.grey.shade100,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 16,
                    vertical: 10,
                  ),
                ),
                onSubmitted: (_) => _sendMessage(),
              ),
            ),
            const SizedBox(width: 8),
            if (_sending)
              const Padding(
                padding: EdgeInsets.all(8),
                child: SizedBox(
                  width: 24,
                  height: 24,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              )
            else
              CircleAvatar(
                backgroundColor: const Color(0xFF1565C0),
                child: IconButton(
                  icon: const Icon(Icons.send, color: Colors.white, size: 18),
                  onPressed: _sendMessage,
                ),
              ),
          ],
        ),
      ),
    );
  }
}

//  MESSAGE BUBBLE - Displays text or media messages with appropriate styling. Decrypts message content for display and handles media types (images/videos) with previews.

class _MessageBubble extends StatelessWidget {
  final Map<String, dynamic> msg;
  final bool isMe;

  const _MessageBubble({required this.msg, required this.isMe});

  @override
  Widget build(BuildContext context) {
    final time = DateTime.parse(msg['created_at'] as String).toLocal();
    final timeStr = '${time.hour}:${time.minute.toString().padLeft(2, '0')}';

    if (msg['is_key_exchange'] == true) {
      return Center(
        child: Container(
          margin: const EdgeInsets.symmetric(vertical: 8),
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
          decoration: BoxDecoration(
            color: Colors.grey.shade200,
            borderRadius: BorderRadius.circular(12),
          ),
          child: Text(
            msg['decrypted_content'] as String,
            style: const TextStyle(fontSize: 12, color: Colors.grey),
          ),
        ),
      );
    }

    Widget content;
    if (msg['media_type'] == 'image') {
      content = ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: Image.network(
          msg['media_url'] as String,
          width: 200,
          fit: BoxFit.cover,
          loadingBuilder: (_, child, progress) => progress == null
              ? child
              : const SizedBox(
                  width: 200,
                  height: 140,
                  child: Center(child: CircularProgressIndicator()),
                ),
        ),
      );
    } else if (msg['media_type'] == 'video') {
      content = _VideoPreview(url: msg['media_url'] as String);
    } else {
      content = Text(
        msg['decrypted_content'] as String? ?? '',
        style: TextStyle(
          color: isMe ? Colors.white : Colors.black87,
          fontSize: 15,
        ),
      );
    }

    return Align(
      alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.symmetric(vertical: 4),
        padding: const EdgeInsets.all(10),
        constraints: BoxConstraints(
          maxWidth: MediaQuery.of(context).size.width * 0.75,
        ),
        decoration: BoxDecoration(
          color: isMe ? const Color(0xFF1565C0) : Colors.grey.shade200,
          borderRadius: BorderRadius.only(
            topLeft: const Radius.circular(18),
            topRight: const Radius.circular(18),
            bottomLeft: Radius.circular(isMe ? 18 : 4),
            bottomRight: Radius.circular(isMe ? 4 : 18),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            content,
            const SizedBox(height: 4),
            Text(
              timeStr,
              style: TextStyle(
                fontSize: 10,
                color: isMe ? Colors.white70 : Colors.grey.shade600,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _VideoPreview extends StatefulWidget {
  final String url;
  const _VideoPreview({required this.url});

  @override
  State<_VideoPreview> createState() => _VideoPreviewState();
}

class _VideoPreviewState extends State<_VideoPreview> {
  late VideoPlayerController _controller;
  bool _initialized = false;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.networkUrl(Uri.parse(widget.url))
      ..initialize().then((_) {
        if (mounted) setState(() => _initialized = true);
      });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_initialized) {
      return const SizedBox(
        width: 200,
        height: 120,
        child: Center(child: CircularProgressIndicator()),
      );
    }
    return GestureDetector(
      onTap: () => setState(() {
        _controller.value.isPlaying ? _controller.pause() : _controller.play();
      }),
      child: Stack(
        alignment: Alignment.center,
        children: [
          SizedBox(
            width: 200,
            child: AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              child: VideoPlayer(_controller),
            ),
          ),
          if (!_controller.value.isPlaying)
            Container(
              decoration: const BoxDecoration(
                color: Colors.black45,
                shape: BoxShape.circle,
              ),
              padding: const EdgeInsets.all(8),
              child: const Icon(
                Icons.play_arrow,
                color: Colors.white,
                size: 32,
              ),
            ),
        ],
      ),
    );
  }
}
